server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  error:
    whitelabel:
      enable: false
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
    http2:
      enabled: true
    jetty:
      threads:
        acceptors: 120

spring:
  application:
    name: api-clientes
  profiles:
    active: ${ENV_PROFILE:local}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/clientes}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER_NAME:root}
    password: ${DATABASE_USER_PASSWORD:root}
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#  spring.security.user.name=username
#  spring.security.user.password=password

#  flyway:
#    url: ${spring.datasource.url}
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    out-of-order: true
feign:
  hystrix:
    enabled: true
springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: ['POST','PUT','GET','DELETE']

client:
  viacep:
    host: ${VIACEP_HOST:https://viacep.com.br/ws}

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}